name: Build Stable Release

on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        type: string
        description: Chunky reference to build. Branch or tag.
      ver:
        required: true
        type: string
        description: Version name. SemVer compliant version.
      notes:
        required: true
        type: string
        description: Comment ID for release notes.

jobs:
  build_stable:
    uses: ThatRedox/ChunkyUpdateSite/.github/workflows/chunky_build.yaml@master
    with:
      ref: ${{ github.event.inputs.ref }}
      ver: ${{ github.event.inputs.ver }}
      notes: ${{ github.event.inputs.notes }}

  deploy_stable:
    needs: build_stable
    uses: ThatRedox/ChunkyUpdateSite/.github/workflows/deploy_branch.yaml@master
    with:
      branch_name: release-stable

  deploy_page:
    needs: deploy_stable
    uses: ThatRedox/ChunkyUpdateSite/.github/workflows/deploy_pages.yaml@master
