# This builds the latest version of chunky.
name: Build Chunky

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone Chunky Repository
        uses: actions/checkout@v2
        with:
          repository: chunky-dev/chunky
          fetch-depth: 0
      
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jdk+fx
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build Chunky
        run: ./gradlew -PnewVersion="$(git describe)"
      
      - name: Include release files.
        run: cp latest.json build/latest.json && cp -r chunky/lib/* build/
      
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          name: Chunky Build
          path: build/

  deploy:
    runs-on: ubuntu-20.04
    needs: build
    
    steps:
      - name: Clone Update Site Repository
        uses: actions/checkout@v2
      
      - name: Get Artifacts
        uses: actions/download-artifact@v2
        with:
          name: Chunky Build
      
      - name: Create and Commit GH Pages Branch
        run: |
          git checkout --orphan gh-pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Actions Build"
          git push -f
      
