name: Internal Build Chunky

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      ver:
        required: true
        type: string
      notes:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone Chunky Repository
        uses: actions/checkout@v2
        with:
          repository: chunky-dev/chunky
          ref: ${{ inputs.ref }}
          fetch-depth: 0
      
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jdk+fx
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Calculate release name
        id: release_name
        run: echo "::set-output name=result::${{ inputs.ver }}"

      - name: Get release notes
        uses: actions/github-script@v5
        id: release_notes
        with:
          result-encoding: string
          script: |
            return github.rest.issues.getComment({
              "ThatRedox",
              "ChunkyUpdateSite",
              ${{ inputs.notes }}
            }).body;

      - name: Save release notes
        run: echo "${{ steps.release_notes.outputs.result }}" > "release_notes-${{ steps.release_name.outputs.result }}.txt"
      
      - name: Build Chunky
        run: ./gradlew -PnewVersion=${{ steps.release_name.outputs.result }}
      
      - name: Include release files and cleanup.
        run: |
          rm -rf build/tmp/
          mkdir build/lib/
          cp latest.json build/latest.json
          cp -r chunky/lib/* build/lib/
      
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          name: Chunky Build
          path: build/
