name: Internal Deploy Pages

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone update site repository branch gh-pages
        uses: actions/checkout@v2
        with:
          path: ./gh-pages

      - name: Create gh-pages branch
        working-directory: gh-pages
        run: |
          git checkout --orphan gh-pages
          git rm . -r -f
          mkdir lib

      - name: Clone update site repository branch master
        uses: actions/checkout@v2
        with:
          path: ./master

      - name: Copy static site files to site
        run: |
          cp -r ./master/site/* ./gh-pages/

      - name: Clone update site repository branch release-stable
        uses: actions/checkout@v2
        with:
          path: ./stable
          ref: release-stable

      - name: Add stable build to site
        run: |
          cp ./stable/latest.json ./gh-pages/latest.json
          cp -r ./stable/lib/ ./gh-pages/

      - name: Clone update site repository branch release-beta
        uses: actions/checkout@v2
        with:
          path: ./beta
          ref: release-beta

      - name: Add beta build to site
        run: |
          cp ./beta/latest.json ./gh-pages/snapshot-stable.json
          cp -r ./beta/lib/ ./gh-pages/

      - name: Clone update site repository branch release-snapshot
        uses: actions/checkout@v2
        with:
          path: ./snapshot
          ref: release-snapshot

      - name: Add nightly snapshot to site
        run: |
          cp ./snapshot/latest.json ./gh-pages/snapshot.json
          cp -r ./snapshot/lib/ ./gh-pages/

      - name: Commit gh-pages branch
        working-directory: gh-pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Actions Build"
          git push --force --set-upstream origin gh-pages
